<a href="https://colab.research.google.com/github/paty3090/AT05-Funcoes/blob/main/AT05_Funcoes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Crie uma função chamada calcula_imc(peso=70, altura=1.75) que retorne o valor do IMC.
(Fórmula: peso / altura²)



In [3]:
#Funcao calcula_imc:
70 / 1.75

40.0

2) Dado uma lista chamada alturas com os seguintes elementos: 45, 23, 67, 12, 11, 89, 23, 41, 50, 62, 78, 34, 56, 19, 72, 88, 11, 90, 39, 65, 76, 27, 48, 59, 81, 14, 11, 93, 3, 68, 29, 52, 74, 16, 85, 20, 55, 38, 69, 11, 83, 7, 44, 61, 18, 96, 22, 58, 31, 71, 40, 53, 87, 31.



Utilize as funções padrão do Python para calcular e exibir:
O maior valor do conjunto de dados;
O menor valor do conjunto de dados;
A soma de todos os valores;
O valor absoluto de um número negativo (-25);
O arredondamento do número 3.14159 para 2 casas decimais.


In [5]:
print('Valor absoluto (negativo): ', abs(-25))
medidas = [45, 23, 67, 12, 11, 89, 23, 41, 50, 62, 78, 34, 56, 19, 72, 88, 11, 90, 39, 65, 76, 27, 48, 59, 81, 14, 11, 93, 3, 68, 29, 52, 74, 16, 85, 20, 55, 38, 69, 11, 83, 7, 44, 61, 18, 96, 22, 58, 31, 71, 40, 53, 87, 31.]
print('Maior valor: ', max(medidas))
print('Menor valor: ', min(medidas))
print('Soma: ', sum(medidas))
print('Arredondamento', round(3.14159, 2))

Valor absoluto (negativo):  25
Maior valor:  96
Menor valor:  3
Soma:  2606.0
Arredondamento 3.14


Utilize as funções do módulo statistics para calcular e exibir:
A média dos dados;
A mediana dos dados;
A moda dos dados;
A variância da amostra dos dados;
O desvio padrão da amostra dos dados.

In [6]:
# Estatística
from statistics import *
print('Média: ', mean(medidas))
print('Mediana: ', median(medidas))
print('Moda: ', mode(medidas))
print('Variância: ', variance(medidas))
print('Desvio padrão: ', stdev(medidas))

Média:  48.25925925925926
Mediana:  49.0
Moda:  11
Variância:  741.1013277428372
Desvio padrão:  27.223176297831913


3) Crie duas matrizes aleatórias:
Uma matriz 5x10 de números float aleatórios entre 0 e 1.
Uma matriz 8x4 de números inteiros aleatórios entre 0 e 9.

In [10]:
import numpy as np

# Matriz 5x10 de floats entre 0 e 1
matriz_float = np.random.rand(5, 10)
print("Matriz 5x10 de floats entre 0 e 1:")
print(matriz_float)

Matriz 5x10 de floats entre 0 e 1:
[[0.92618506 0.93578084 0.61394321 0.48240005 0.45864439 0.44840121
  0.56316009 0.43228282 0.46191376 0.39873519]
 [0.36570825 0.7399029  0.23886971 0.97904284 0.09020299 0.17149865
  0.61010998 0.39653417 0.49500759 0.68758775]
 [0.73221152 0.21498142 0.77841806 0.82689638 0.58115976 0.4985312
  0.70027872 0.61056247 0.60673284 0.73438751]
 [0.04190624 0.19014796 0.1179548  0.78910075 0.59379869 0.30220244
  0.80556006 0.44972371 0.8248761  0.56847986]
 [0.3463542  0.10029606 0.87793897 0.01350827 0.31980498 0.92518852
  0.44339834 0.55542246 0.81174962 0.8944547 ]]


In [11]:
# Matriz 8x4 de inteiros entre 0 e 9
matriz_int = np.random.randint(0, 10, size=(8, 4))
print("\nMatriz 8x4 de inteiros entre 0 e 9:")
print(matriz_int)


Matriz 8x4 de inteiros entre 0 e 9:
[[6 7 9 7]
 [8 7 7 9]
 [1 3 1 7]
 [8 8 0 5]
 [0 7 8 6]
 [2 1 1 0]
 [0 3 8 5]
 [6 4 2 8]]
